### ISSUE TITLE
Completion endpoint is prepending "data: " in front of streaming JSON objects

### ISSUE THREAD

**Issue by cikkle** [theroyallab/tabbyAPI#10]
When streaming is enabled in the request body, instead of just returning the JSON string, "data: " is added to the front of each response. I have to chop it off before parsing.

![Screenshot_20231119_022713](https://github.com/theroyallab/tabbyAPI/assets/136946368/cf6325b9-976a-41f4-a412-96cbbd1690b5)

**Comment by bdashore3** [comment]
This is intended. Please look at documentation for the EventSource API and SSE events:

https://developer.mozilla.org/en-US/docs/Web/API/EventSource

https://javascript.info/server-sent-events

So, on a message, you'll need to grab the object via `e.data`
