### ISSUE TITLE
[REQUEST] How do i disable cache? 

### ISSUE THREAD

**Issue by Curiosity007** [theroyallab/tabbyAPI#115]
I dont want to use cache at all. Rather I would like to generate the response from scratch, so , all new tokens. How do i do it

**Comment by turboderp** [comment]
Can you elaborate on why?

**Comment by turboderp** [comment]
It depends very much on the model and what you're trying to make it do (or not do.) Some models can be very stubborn and not very creative at all. If you ask Llama3-instruct anything remotely dangerous, controversial or lewd, its response will almost always start with "I cannot provide," no matter how you try to tweak the prompt.

You could play with sampling parameters, like temperature which flattens the output distribution making the model less stable and predictable (for better or worse). There's skew which, well, skews the distribution and can bias the model towards its second or third choice for any given token. That can give some interesting generations if nothing else. The banned strings feature suppresses exact strings (like "I cannot provide" or "as an AI language model"), and if you're trying to make the model reliably conform to a format like a JSON schema, you can generate with that schema as a constraint.

Mostly I'd say make sure you've tried some different models. ChatGPT is tough to beat if that's what you're comparing to, but Llama3-instruct is still very good at taking directions, for instance.

**Comment by turboderp** [comment]
>Even for change in prompt? Should not that prompt be consumed as a whole to see whether the underlying meaning has changed or not (attention) , and based on that kv should be generated?

Decoder-only models (most modern LLMs) use only causal attention, meaning that everything is evaluated left-to-right. Even when processing all the prompt tokens in parallel, this is still done with a causal mask. So changing the token at position 100 has no effect on how tokens 0-99 are interpreted, but it does affect every token *after* position 100.
