### ISSUE TITLE
[REQUEST] Support array type content for OAI API

### ISSUE THREAD

**Issue by RockChinQ** [theroyallab/tabbyAPI#117]
**Is your feature request related to a problem? Please describe.**

OAI API now supports following two kinds of  `messages.*.content` in `ChatCompletionRequest`
https://platform.openai.com/docs/api-reference/chat/create

```python
# string
  messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Hello!"}
  ]
```

and 

```python
# array (for multi-modal)
    messages=[
        {
            "role": "user",
            "content": [
                {"type": "text", "text": "What's in this image?"},
                {
                    "type": "image_url",
                    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg",
                },
            ],
        }
    ],
```

Although this API may not pass images, it may still pass text content in the form of an array.

```json
    messages=[
        {
            "role": "user",
            "content": [
                {"type": "text", "text": "What's in this image?"},
            ],
        }
    ],
```

and then we got the error msg :)

```
Error code: 422 - {'detail': [{'type': 'string_type', 'loc': ['body', 'messages', 'str'], 'msg': 'Input should be a valid string', 'input': [{'role': 'system', 'content': ''}, {'role': 'user', 'content': [{'type': 'text', 'text': '你好'}]}]}, {'type': 'string_type', 'loc': ['body', 'messages', 'list[dict[str,str]]', 1, 'content'], 'msg': 'Input should be a valid string', 'input': [{'type': 'text', 'text': '你好'}]}]}
```

**Describe the solution you'd like**

https://github.com/theroyallab/tabbyAPI/blob/e95e67a000a5e697a9f60f1358c8b8654d477819/endpoints/OAI/types/chat_completion.py#L41-L44

Update this model of `content` and the backend converting logic. Thank you.

**Describe alternatives you've considered**
Client can pre-process the data, but OAI official API supports the case above.

**Why should this feature be added?**
OAI official API supports this case, and some clie/nt will not convert the text-only array to a string automatically.

**Examples**
```
content=[{'role': 'system', 'content': ''}, {'role': 'user', 'content': [{'type': 'text', 'text': '你好'}]}]
```

**Additional context**

/

**Comment by Orion-zhen** [comment]
The PR has been merged, so you could safely close this issue : -)
