### ISSUE TITLE
[REQUEST] model loading in oAI endpoint

### ISSUE THREAD

**Issue by lucyknada** [theroyallab/tabbyAPI#118]
a lot of tools now allow to set different oAI models for different tasks, this would be extremely useful to have in tabby, since you could actually make use of the "model" key in the payload

one such tool example would be: https://www.continue.dev/ which has different models for tab-completion and regular chat suggestions (each a distinct model)

implementation could check if the model exists in the models folder and if not, simply does the same as now; generate with the currently loaded model instead.

alternatives considered: proxy that fronts tabby and checks the models folder for if such model exists and loads it, but that has proven itself awkward.

thanks!

**Comment by lucyknada** [comment]
in router.py completion_request, something as simple as:

```python
current_model = unwrap(model.container.get_model_parameters().pop("name", None), "unknown")
if data.model and data.model != current_model:
    try:
        model_config = config.model_config()
        model_path = pathlib.Path(unwrap(model_config.get("model_dir"), "models"))
        model_path = model_path / data.model
        await model.load_model(model_path.resolve(), **model_config)
    except Exception as e:
        # log model load failure; fall-back to generating with currently loaded model
        pass
  ```      

works for my use-case, but that doesn't cover probably the 10s of other functions something like this feature-request should entail, e.g. applying loras just like on boot-up, maybe extracting model-loading into its own util etc, just leaving it here in case someone else wants a quick band-aid, until this is considered as an upstream feature.

also up for debate if a failure of the model should actually fail the request too (e.g. via 404) or just fall-back to generating with whatever is loaded (or not loaded) since that could affect tools that request gpt3.5, which doesn't per se exist in the models folder..

**Comment by lucyknada** [comment]
further thoughts as someone has brought this to my attention: currently the above simply loads in the current model_config, which could be problematic if you switch to e.g. a too big model

this could be alleviated by simply having a model_config in the payload that is used to initialize the new model with those parameters, re-using the same config args as CLI and config use already

**Comment by bartowski1182** [comment]
Oh hey, I had a similar idea and opened a PR here:

https://github.com/theroyallab/tabbyAPI/pull/130

You can test it yourself, worked for me with open-webui

**Comment by bdashore3** [comment]
Added in #130 and #183
