### ISSUE TITLE
[REQUEST] Official Docker/GHCR image for quick testing/reproduction/etc

### ISSUE THREAD

**Issue by josephrocca** [theroyallab/tabbyAPI#123]
**Is your feature request related to a problem? Please describe.**
For ease of testing + getting started + easily reproducible and versioned bug reports, it'd be nice to be able to paste a repo ID in a Runpod/Salad/etc. template, set a `TABBY_CONFIG` (or whatever) environment variable, and hit deploy.

**Describe the solution you'd like**
An official container image on docker.io or ghcr.io. The `TABBY_CONFIG` environment variable would allow setting specific properties like:

```
TABBY_CONFIG="port:4000; host:0.0.0.0;"
```
or something like that.

**Why should this feature be added?**
It would make getting started with tabby super easy for those who use Runpod and similar cloud services. I know this project isn't for production usage, but it would still be helpful for a lot of users I think.

**Comment by DocShotgun** [comment]
If you want to run tabby on runpod, Wolfsauge is building auto-building docker images for it to keep up with the latest main branch:

https://github.com/Wolfsauge/podman_build_tabbyapi/

**Comment by av** [comment]
Whomever lands here from search, here's the Docker Hub handle of the mentioned images:
https://hub.docker.com/r/nschle/tabbyapi/tags
(kudos to the Wolfsauge for setting up the CI)

**Comment by bdashore3** [comment]
Resolved via #171
