### ISSUE TITLE
AssertionError: Filter excluded all tokens

### ISSUE THREAD

**Issue by cikkle** [theroyallab/tabbyAPI#127]
**Describe the bug**
I'm using the json_schema feature to constrain completion output and while it seems to work for schemas with a top-level object, it fails when I try to use an array at the root. Upon sending a request nothing happens until I ctrl+c and get the exception further below.

**To Reproduce**
This is a simple test schema I'm using, it passes in online validators:

```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "string"
    }
}
```

I send it to the api with an empty prompt. The other parameters look like this:

{
        "max_tokens": 1000,
        "generate_window": 512,
        "token_healing": true,
        "temperature_last": true,
        "add_bos_token": true,
        "ban_eos_token": false,
        "json_schema": (schema goes here),
        "stream": true,
        "response_format": { "type": "json_object" },
        "prompt": "",
        "temperature": 0.7,
        "top_p": 0.9,
        "top_k": 20,
        "typical_p": 1,
        "top_a": 0,
        "tfs": 1,
        "repetition_penalty": 1.15,
        "repetition_penalty_range": 0,
        "num_beams": 1,
        "length_penalty": 1,
        "encoder_rep_pen": 1,
        "do_sample": true,
        "early_stopping": false,
        "mirostat_mode": 0,
        "mirostat_tau": 5,
        "mirostat_eta": 0.1
}

**Expected behavior**
I expected it to work without error and constrain the output to something simple like:

>[ "hello" ]

**Logs**

> INFO:     ExllamaV2 version: 0.1.3
> INFO:     Your API key is: 
> INFO:     Your admin key is: 
> INFO:     
> INFO:     If these keys get compromised, make sure to delete api_tokens.yml and restart the server. Have fun!
> INFO:     Generation logging is disabled
> WARNING:  An unsupported GPU is found in this configuration. Switching to compatibility mode. 
> WARNING:  This disables parallel batching and features that rely on it (ex. CFG). 
> WARNING:  To disable compatability mode, all GPUs must be ampere (30 series) or newer. AMD GPUs are not supported.
> INFO:     Attempting to load a prompt template if present.
> INFO:     Using template "default" for chat completions.
> INFO:     Loading model: /home/o0/ai/models/text/command-r-v01-35B-exl2
> INFO:     Loading with autosplit
> Loading model modules ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 43/43 0:00:00
> INFO:     Model successfully loaded.
> INFO:     Developer documentation: http://0.0.0.0:5000/redoc
> INFO:     Completions: http://0.0.0.0:5000/v1/completions
> INFO:     Chat completions: http://0.0.0.0:5000/v1/chat/completions
> INFO:     Started server process [184921]
> INFO:     Waiting for application startup.
> INFO:     Application startup complete.
> INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
> INFO:     192.168.50.17:37980 - "POST /v1/completions HTTP/1.1" 200
> ERROR:    Completion generation cancelled by user.
> ERROR:    Task exception was never retrieved
> ERROR:    future: \<Task finished name='Task-11' coro=\<_stream_collector() done, defined at /home/o0/ai/tabbyAPI/endpoints/OAI/utils/completion.py:76> 
> exception=AssertionError('Filter excluded all tokens')>
> ERROR:    Traceback (most recent call last):
> ERROR:      File "/home/o0/ai/tabbyAPI/endpoints/OAI/utils/completion.py", line 86, in _stream_collector
> ERROR:        async for generation in new_generation:
> ERROR:      File "/home/o0/ai/tabbyAPI/backends/exllamav2/model.py", line 1087, in generate_gen
> ERROR:        async for result in job:
> ERROR:      File "/home/o0/.local/lib/python3.10/site-packages/exllamav2/generator/dynamic_async.py", line 84, in __aiter__
> ERROR:        raise result
> ERROR:      File "/home/o0/.local/lib/python3.10/site-packages/exllamav2/generator/dynamic_async.py", line 26, in _run_iteration
> ERROR:        results = self.generator.iterate()
> ERROR:      File "/home/o0/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
> ERROR:        return func(*args, **kwargs)
> ERROR:      File "/home/o0/.local/lib/python3.10/site-packages/exllamav2/generator/dynamic.py", line 882, in iterate
> ERROR:        self.iterate_gen(results)
> ERROR:      File "/home/o0/.local/lib/python3.10/site-packages/exllamav2/generator/dynamic.py", line 1101, in iterate_gen
> ERROR:        job.receive_logits(job_logits)
> ERROR:      File "/home/o0/.local/lib/python3.10/site-packages/exllamav2/generator/dynamic.py", line 1570, in receive_logits
> ERROR:        ExLlamaV2Sampler.sample(
> ERROR:      File "/home/o0/.local/lib/python3.10/site-packages/exllamav2/generator/sampler.py", line 247, in sample
> ERROR:        assert pass_tokens, "Filter excluded all tokens"
> ERROR:    AssertionError: Filter excluded all tokens

**System info**
Ubuntu 22.04.4 LTS
Python 3.10.12
ROCm 6.1.1

**Comment by DocShotgun** [comment]
Hmmm I think the reason for this is that the JSON schema filter in TabbyAPI forces a prefix of `{` assuming that the output is a JSON object, but your schema results in a JSON array instead, that begins with `[`. As a result there are no valid tokens that can be sampled.

**Comment by cikkle** [comment]
Commenting it out just makes it complain further down that `prefix_filter` isn't defined, but I tried changing the prefix to `"["` and it works, so indeed the problem lies there.

**Comment by cikkle** [comment]
I pulled the latest versions of exllama and tabbyapi after turboderp's commit and top level arrays are working fine. Thanks all.
