### ISSUE TITLE
[BUG] Docker workflow is not working properly

### ISSUE THREAD

**Issue by AmgadHasan** [theroyallab/tabbyAPI#149]
**Disclaimer:** Github Issues are **only** for code related bugs. If you do not understand how to startup or use TabbyAPI, please ask in the [Discord Server](https://discord.gg/sYQxnuD7Fj)

**Describe the bug**
The instructions for running with docker have a few issues.
First, the docker-compose.yml file is not in the root of the repo so we need to specify its path when starting the container:
```sh
docker compose -f docker/docker-compose.yml up
```
Second, the volume does not get mounted to the correct desintation. It should be as follows:
```
volumes:
    - path/to/models:/app/models  # instead of /usr/src/app/models
```

**To Reproduce**
Follow the instructions from the [wiki](https://github.com/theroyallab/tabbyAPI/wiki/1.-Getting-Started#docker)

**Expected behavior**
The container should start smoothly

**Logs**
If applicable, add logs and tracebacks to help explain your problem.

**System info** (Bugs without this information will go lower on our priority list!)
 - OS: Ubuntu 22.04.03 LTS
 - Docker version: Docker version 27.0.3, build 7d4bcd8

I will open a PR to fix these issues.

**Comment by bdashore3** [comment]
PR merged. Closing this issue.
