### ISSUE TITLE
Possible issues with /v1/chat/completions endpoint.

### ISSUE THREAD

**Issue by yatesdr** [theroyallab/tabbyAPI#15]
Trying this out with Chatbot-UI, which is supposed to be OpenAI compatible and does work with several other back-ends.

Tabby setup:    python-3.11, pip install requirements, exllamav2,  fastchat worker per the readme.md
Front-end:  Chatbot-UI, passing API keys through Bearer method.   models load fine, test endpoints work okay, etc.
Models:  Various, all exl2 from LoneStriker that are confirmed working fine.
OS:  Ubuntu 22.04 LTS, lambda stack, using venv for this on python-3.11, Cuda 12.2, 535.113.01 drivers.

I'm receiving the following error when attempting to start the first chat:

INFO:     127.0.0.1:53510 - "POST /v1/chat/completions HTTP/1.1" 200 OK

Traceback (most recent call last):
  File "/home/xxx/AI/xxx-exllamav2/tabbyAPI/main.py", line 228, in generator
    new_generation, prompt_tokens, completion_tokens = model_container.generate_gen(prompt, **data.to_gen_params())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 3)

Pretty vanilla install, but it's possible I have something configured wrong.   Any suggestions are welcome, this looks like a fantastic project!

**Comment by yatesdr** [comment]
A little more info here.... added some print statements to model.py in the generator_gen / yield area.   It appears to start generation okay after an unprompted answer about a 10 year old's birthday party, but quickly errors out for unknown reasons.

INFO:     127.0.0.1:49058 - "POST /v1/chat/completions HTTP/1.1" 200 OK
Prompt:  You are ChatBot, a large language model trained by many smart people. Follow the user's instructions carefully. Respond using markdown.
### Human: Got any creative ideas for a 10 year old’s birthday?
### Assistant: Of course! Here are some creative ideas for a 10-year-old's birthday party:
1. Treasure Hunt: Organize a treasure hunt _(... truncated, it goes on for a while about ideas)._
### Human: Tell me a story about llamas.
### Assistant:
Type kwargs:  <class 'dict'>
Len kwargs:  18
KWargs:  {'stop': [], 'max_tokens': 1000, 'add_bos_token': True, 'ban_eos_token': False, 'token_healing': False, 'temperature': 0.5, 'temperature_last': False, 'top_k': 0, 'top_p': 1.0, 'typical': 0.0, 'min_p': 0.0, 'tfs': 1.0, 'repetition_penalty': 1.0, 'repetition_range': -1, 'repetition_decay': 0, 'mirostat': False, 'mirostat_tau': 1.5, 'mirostat_eta': 0.1}
Yielding:
Chunk Buffer  Once
Prompt Tokens:  585
Generated Tokens:  1
Chunk Buffer Type, Len <class 'str'>
Prompt Token Type, Len <class 'int'>
Generated Tokens Type, Len <class 'int'>
Yielding:
Chunk Buffer  upon
Prompt Tokens:  585
Generated Tokens:  2
Chunk Buffer Type, Len <class 'str'>
Prompt Token Type, Len <class 'int'>
Generated Tokens Type, Len <class 'int'>
Yielding:
Chunk Buffer  a
Prompt Tokens:  585
Generated Tokens:  3
Chunk Buffer Type, Len <class 'str'>
Prompt Token Type, Len <class 'int'>
Generated Tokens Type, Len <class 'int'>
Yielding:
Chunk Buffer  time
Prompt Tokens:  585
Generated Tokens:  4
Chunk Buffer Type, Len <class 'str'>
Prompt Token Type, Len <class 'int'>
Generated Tokens Type, Len <class 'int'>

Traceback (most recent call last):
  File "/home/xxx/AI/xxx-exllamav2/tabbyAPI/main.py", line 228, in generator
    new_generation, prompt_tokens, completion_tokens = model_container.generate_gen(prompt, **data.to_gen_params())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 3)

**Comment by bdashore3** [comment]
Hey there, thanks for the information! I tested against chatbot-ui and everything should be working with the following commits:
aef411bed5e5b67853c3124d3d915640550cb24a
6493b1d2aae0de7d84a52d1369464e1b3baa7176

Make sure to enable `use_dummy_models` under the `model` subsection of `config.yml`. The sample has been updated with the new parameter.

**Comment by yatesdr** [comment]
> Hey there, thanks for the information! I tested against chatbot-ui and everything should be working with the following commits: [aef411b](https://github.com/theroyallab/tabbyAPI/commit/aef411bed5e5b67853c3124d3d915640550cb24a) [6493b1d](https://github.com/theroyallab/tabbyAPI/commit/6493b1d2aae0de7d84a52d1369464e1b3baa7176)
> 
> Make sure to enable `use_dummy_models` under the `model` subsection of `config.yml`. The sample has been updated with the new parameter.

Typically in deployments with chatbot-ui, the model list is edited in types/openai.ts to include the models you want available.   In this case I think the dummy model may not be needed.

thank you for the fix and I’ll try it out as soon asap.

**Comment by yatesdr** [comment]
Confirmed working.   For other's reference, with chatbot-ui editing the openai types file with new models does appear to work, but model loading does not.

Closing issue as complete.
