### ISSUE TITLE
[REQUEST] Could there be a flag to print the raw request?

### ISSUE THREAD

**Issue by meditans** [theroyallab/tabbyAPI#153]
**Is your feature request related to a problem? Please describe.**
When there are interoperability issues between another library (like `textgrad`) and the tabbyAPI server, I struggle to see which part is at fault.

**Describe the solution you'd like**
I would like to have a switch that prints the raw request to the server.

**Describe alternatives you've considered**
This can be done on the other side, but then I have to do it many times. We also could have logs instead of printing to the screen (but I prefer printing to the screen)

**Comment by bdashore3** [comment]
Added in 3826815

**Comment by bdashore3** [comment]
Closing due to resolution in upstream and inactivity.
