### ISSUE TITLE
[REQUEST] ExLlamaV2 Update

### ISSUE THREAD

**Issue by ccrvlh** [theroyallab/tabbyAPI#156]
Update ExLlamaV2 to 0.1.18 to run Llama 3.1
Right now this is pinned at 0.1.17 on pyproject.
Happy to contribute to this.

**Comment by Master-Pr0grammer** [comment]
Came here to suggest same thing. super hyped for new llama 3.1 features lol.

**Comment by bdashore3** [comment]
Already added in https://github.com/theroyallab/tabbyAPI/commit/a1c3f6cc1cc13d1f52c28bd6a11adb5b05fc8a19
