### ISSUE TITLE
[REQUEST] Add draft model config to cli launch parameters

### ISSUE THREAD

**Issue by arbi-dev** [theroyallab/tabbyAPI#160]
Unlike with most config parameters, configuration of the draft models cannot be done at runtime via command-line arguments.   Unfortunately editing config.yml file is not feasible in environments like kubernetes without rebuilding the docker image.

Please add all the parameters for draft models that are currently in the config.yml to the command line argument specs.

**Comment by bdashore3** [comment]
Resolved in #189
