### ISSUE TITLE
[REQUEST] Implementation of DRY sampler (Don't Repeat Yourself)

### ISSUE THREAD

**Issue by Abdulhanan535** [theroyallab/tabbyAPI#164]
### Problem

Majority of the bots repeat sentences and due to that, it's annoying.

### Solution

Implementing DRY sampler for TabbyAPI

### Explanation

DRY is a sampler that forces the model to not repeat while mantaining the quality or even improving it, some of the backends have already support for this.

- Text Gen webui
- koboldai
- llamaccp

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by bdashore3** [comment]
See issue https://github.com/turboderp/exllamav2/issues/447

If it's added in upstream, I can add it here.

**Comment by Abdulhanan535** [comment]
is it done?
