### ISSUE TITLE
[BUG] speculative decoding too slow

### ISSUE THREAD

**Issue by randoentity** [theroyallab/tabbyAPI#166]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.11

### Describe the bug

When running exllamav2's inference_speculative.py example with llama 3.1 8B 2.25bpw as draft and 70B 4.5bpw as main model I get:

speed, -SD: 18.05 tokens/second                                   
speed, +SD: 29.66 tokens/second

With tabbyAPI to SillyTavern I get between 18 and 20 t/s. This is with 2x3090ti at 300W. I usually run at 150W but then the t/s when using SD is halved compared to no SD with 150W via tabbyAPI. With just exllamav2 it is: 
speed, -SD: 11.65 tokens/second
speed, +SD: 11.34 tokens/second

I've tried to clone the exllamav2 conda env and use it for tabbyAPI, which then still installs some other packages (python -m pip install -e .) but keeps using some key packages from exllamav2, including itself and torch. 

I'm using mostly default settings as far as I'm aware and I've flipped pretty much everything. Sequence length is at 4k on both tabbyAPI as well as exllamav2. 

The same thing happens with Mistral Large and v0.3 as draft model.

Any help is appreciated.

### Reproduction steps

Conda install of tabbyAPI and SillyTavern on headless Linux.
Load the models and run inference using SillyTavern.

### Expected behavior

1.5x speedup :)

### Logs

Sorry for  the formatting.

python main.py                                                              INFO:     ExllamaV2 version: 0.1.8                                          WARNING:  EXPERIMENTAL: Running program with Uvloop/Winloop.                WARNING:  EXPERIMENTAL: Process priority set to Realtime.                   WARNING:  If you're not running on administrator/sudo, the                  priority is set to high.                                                    INFO:     Your API key is: redacted                                         INFO:     Your admin key is: redacted                                       INFO:                                                                       INFO:     If these keys get compromised, make sure to delete                api_tokens.yml and restart the server. Have fun!                            INFO:     Generation logging is disabled                                    WARNING:  The given cache_size (4096) is less than 2 * max_seq_len          and may be too small for requests using CFG.                                WARNING:  Ignore this warning if you do not plan on using CFG.              INFO:     Attempting to load a prompt template if present.
INFO:     Using template "from_tokenizer_config" for chat                   completions.                                                                INFO:     Loading draft model:                                              /mnt/toshi/models/blockblockblock_Meta-Llama-3.1-8B-Instruct-bpw2.25-exl2   INFO:     Loading model:                                                    /mnt/toshi/models/turboderp_Llama-3.1-70B-Instruct-exl2_4.5bpw              INFO:     Loading with autosplit                                            Loading draft modules ━━━━━━━━━━━━━━━━━━━━━━━ 100% 67/67   0:00:00          Loading model modules ━━━━━━━━━━━━━━━━━━━━━━━ 100% 163/163 0:00:00
INFO:     Model successfully loaded.                                        INFO:     Developer documentation: http://0.0.0.0:5000/redoc                INFO:     Starting OAI API
...
INFO:     Finished streaming completion request                             8791ea59445442a0939b1f6c7fae5f52                                            INFO:     Metrics (ID: redacted?): 401               tokens generated in 21.54 seconds (Queue: 0.0 s, Process: 0 cached          tokens and 1156 new tokens at 490.67 T/s, Generate: 20.9 T/s,               Context: 1156 tokens)

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by DocShotgun** [comment]
The effectiveness of speculative decoding can be extremely variable, and depends on the how often the "draft" created by the smaller model is correct. It works very well for formulaic content, like code generation, but isn't as effective for things like creative writing or RP (which I'm assuming is your use case in SillyTavern).

It's hard to say for sure, but it's entirely possible that speculative decoding just performs far worse in your real-world use case than in the provided example script.

**Comment by randoentity** [comment]
Thanks, that's it! I knew it had to be something obvious I was missing. I've tested it again with the exllamav2 example. It actually has a RP prompt commented out as an example (it was right under my nose this whole time!). With this example there is no gain. As I use LLMs for coding I'm really happy with your answer, as I'd have passed off SD as not working. The proof is in the pudding though. If anyone is interested in effectiveness of SD with real-world coding tasks I'll report back.

**Comment by randoentity** [comment]
Alas, with Mistral large I only get 5t/s instead of ~14t/s with Aider outputting only code (I think).
