### ISSUE TITLE
[BUG] docker-compose invalid after latest change

### ISSUE THREAD

**Issue by sab666** [theroyallab/tabbyAPI#169]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.12

### Describe the bug

Because of the most recent changes to docker-compose.yml in in https://github.com/theroyallab/tabbyAPI/commit/dae394050e7d30217f0e93b963fe2e590484ee4a#diff-423deb13b7c401b1a7f41ee91c77f722e11d2f317d6a66b546524e8a04cc8b03 this file is no longer valid yaml:
```
$ docker compose -f docker/docker-compose.yml build
validating [...]/docker/docker-compose.yml: services.tabbyapi.volumes must be a list
```

Context: I have created a build pipeline that automatically builds a docker image based on the changes in this repo, and it failed this morning.

### Reproduction steps

1. checkout the repo
2. run `docker compose -f docker/docker-compose.yml build`
3. See validation error

### Expected behavior

The pipeline would build.

### Additional context

Suggestion: uncomment the placeholder volumes (leave the `# Change me` part), so that the docker-compose.yml file can still be used as-is to build the container.

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by bdashore3** [comment]
That suggestion should fix this issue. However, it's best to keep the models line uncommented since a config.yml and auth_keys.yml have the possibility to not exist.

CC @AmgadHasan

**Comment by bdashore3** [comment]
Try on commit ecaddec48abacc25ac363e92f242b485d9c77ad6

**Comment by sab666** [comment]
Hooray, [pipelines be happy once more](https://gitlab.com/sab_from_earth/tabbyapi/-/pipelines)! :D 

In case somebody else would like to use this image without having to build it themselves, it's available on registry.gitlab.com/sab_from_earth/tabbyapi/sab-from-earth-tabbyapi:latest

**Comment by bdashore3** [comment]
@sab666 would it be possible if you can migrate your gitlab pipelines to a github action that publishes the images to GHCR?

**Comment by AmgadHasan** [comment]
> @sab666 would it be possible if you can migrate your gitlab pipelines to a github action that publishes the images to GHCR?
I can create a github action for this!

Will open a pr soon.

**Comment by sab666** [comment]
> @sab666 would it be possible if you can migrate your gitlab pipelines to a github action that publishes the images to GHCR?

I'm not that fluent in github actions, but you can view the gitlab pipeline I used here: https://gitlab.com/sab_from_earth/tabbyapi/-/blob/master/.gitlab-ci.yml

But yeah, would be great if this image building was part of your project.

**Comment by AmgadHasan** [comment]
> @sab666 would it be possible if you can migrate your gitlab pipelines to a github action that publishes the images to GHCR?

Please check out this [PR](https://github.com/theroyallab/tabbyAPI/pull/171)
@bdashore3
