### ISSUE TITLE
[REQUEST] Health check endpoint 

### ISSUE THREAD

**Issue by Immortalin** [theroyallab/tabbyAPI#170]
### Problem

It would be nice to have a way to check the status of the server without manually inspecting logs

### Solution

A health check endpoint at /health that returns 200

### Explanation

It is good site reliability engineering practice to have an automated way of figuring out if a server is online

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by bdashore3** [comment]
Resolved by #178
