### ISSUE TITLE
[REQUEST] Update the docker section in the wiki

### ISSUE THREAD

**Issue by AmgadHasan** [theroyallab/tabbyAPI#182]
### Problem

Hi,

The current section in the wiki for deploying using docker doesn't include the latest changes where we have published docker images. I have modified it to reflect the new changes where the users can choose to use the pre built images and skip the step of building it which takes a lot of time and resources.

cc @br

### Solution
Here is the modified section:
### Building from dockerfile
1. Install Docker and docker compose from the [docs](https://docs.docker.com/compose/install/)
2. Install the Nvidia container compatibility layer
    a. For Linux: [Nvidia container toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)
    b. For Windows: [Cuda Toolkit on WSL](https://docs.nvidia.com/cuda/wsl-user-guide/index.html)
3. Clone TabbyAPI via 
```bash
git clone https://github.com/theroyallab/tabbyAPI
```
4. Enter the tabbyAPI directory by 
```sh
cd tabbyAPI
```
5. Optional: Set up a `config.yml` or `api_tokens.yml` ([configuration](https://github.com/theroyallab/tabbyAPI/wiki/1.-Getting-Started#configuration))
6. Update the volume mount section in the `docker/docker-compose.yml` file
```yml
volumes:
  # - /path/to/models:/app/models                       # Change me
  # - /path/to/config.yml:/app/config.yml               # Change me
  # - /path/to/api_tokens.yml:/app/api_tokens.yml       # Change me
```
7. Run the following to build the docker image and start the server inside the container:
```sh
docker compose -f docker/docker-compose.yml up
```
### Deploying from published image
1. Follow steps 1-6 from `Building from dockerfile`
2. Modify the docker compose file as follows:
```yml
    # Comment out the build section
    # build:
    #   context: ..
    #   dockerfile: ./docker/Dockerfile
    #   args:
    #     - DO_PULL=true
    # Point the compose file to the latest built image
    image: ghcr.io/theroyallab/tabbyapi:latest
```
3. Run the following to build the docker image and start the server inside the container:
```sh
docker compose -f docker/docker-compose.yml up
```

### Explanation

Improve the docs

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by bdashore3** [comment]
Made it more concise with an optional 6th step. Closing.
