### ISSUE TITLE
API request fails with "Method Not Allowed"

### ISSUE THREAD

**Issue by lmg-anon** [theroyallab/tabbyAPI#2]
I get the below error when trying to use the API from a browser:
```
INFO:     127.0.0.1:52663 - "OPTIONS /v1/completions HTTP/1.1" 405 Method Not Allowed
```
(This HTTP request probably is coming from CORS)

**Comment by bdashore3** [comment]
I need more information here. From this log, it looks like you're sending an HTTP `OPTIONS` request for an endpoint that asks for a `POST` request. I'd advise changing the method to POST and trying again.

For my own information, can you please send the steps for reproduction and the request object itself if possible?

**Comment by bdashore3** [comment]
Please check at commit ac4e9c2277c6a71c679b8454028405dd968b669c. I added CORS middleware.

**Comment by bdashore3** [comment]
Thanks for the writeup!

Please see d627d14. It should fix those issues.

**Comment by lmg-anon** [comment]
You're welcome! Everything seems to be working fine now, however, by accident I found a bug, the API Key check is wrong, it allows you to use just one character from the actual API key, for example, `1` when the key is `04184a48b734494d594dbaca0e48ea7a`.
