### ISSUE TITLE
[BUG] Lack of documentation/unable to use JSON/Grammar

### ISSUE THREAD

**Issue by fullstackwebdev** [theroyallab/tabbyAPI#200]
### OS

Windows

### GPU Library

CUDA 12.x

### Python version

3.12

### Describe the bug

Hi thanks the project support EBNF grammar and JSON Schema, however, I am unable to use it
I believe it is broken, but could somebody please document the best practice so I verify my testing?

In any scenario, it fails

### Reproduction steps

Try an JSON or grammar example

### Expected behavior

To get JSON

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by Seikho** [comment]
I've noticed this as well since exllama 0.2.1. Works fine with 0.2.0.

**Comment by DocShotgun** [comment]
This appears to be a problem with LMFE's `ExLlamaV2TokenEnforcerFilter` not including the new functions added in exl2 0.2.1, assuming you got the same error that I did when I tried a minimal example.

For the future though, it would at least be helpful to provide *some* additional information other than "it doesn't work" to diagnose the problem, such as what model was being used/request being sent/traceback of the error.
