### ISSUE TITLE
Issue with API Mixing Conversations in Simultaneous Usage

### ISSUE THREAD

**Issue by stas-smedia** [theroyallab/tabbyAPI#21]
We have encountered a critical issue with the API where it mixes up conversations when two different users are engaging with it simultaneously. This leads to a significant confusion in responses, as the model seems to blend or switch the contexts between the two separate conversations.

Steps to Reproduce:

Start two separate conversation sessions simultaneously.
Engage in distinctly different topics or queries in each session.
Observe the responses over a period of interactions.
Expected Behavior:
The API should maintain separate contexts for each conversation and respond accurately to each user independently.

Actual Behavior:
The API mixes up responses and context between the two conversations, leading to irrelevant or confused answers.

**Comment by bdashore3** [comment]
Fixed and tested on my end with ed6c962aadb8ae74a21520631cf3027ee9057d1c and 5e54911cc81a9d55f4146c48840e452e6d98d676

**Comment by bdashore3** [comment]
Closing because the issue has been open for a long time. The queues have been tested and work fine from multiple users. Please reopen if this issue happens again.
