### ISSUE TITLE
[REQUEST] Automatic Model Unloading while idling

### ISSUE THREAD

**Issue by TetrisBlack** [theroyallab/tabbyAPI#216]
### Problem

The model stays loaded onto VRAM, even after long time of idling. This causes higher Watt usage of the GPU and takes up VRAM that could be used by other programs.

### Solution

Add an auto unload on idle function. Possible options.
IDLE_UNLOAD = true (enables / disables this feature)
IDLE_TIME = 5m (sets the timeout timer)
In this example, after 5 min of not receiving a request, the model gets unloaded. After receiving a new request while the model is unloaded. The model should be then loaded into VRAM again and the 5-min timer start's from the beginning. 

### Explanation

Would reduce the electric bill on 24/7 operation :)

### Examples

https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-completion the keep_alive parameter on ollama

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by atisharma** [comment]
I hope it would be optional if implemented. Loading Mistral Large takes a long time.

**Comment by SecretiveShell** [comment]
This would require having inline model loading enabled in the config

**Comment by bdashore3** [comment]
Inline model loading is a shim for frontends that use an OAI api. This is not the preferred way to load a model and it won't be built upon with newer features. Since the suggested feature is implicit/ambiguous between the client/server contract, it doesn't fall within the scope of tabby.

Models can be loaded/unloaded on demand using the `/v1/model/load` and `/v1/model/unload` endpoints. If you really want this behavior, I would suggest making a script which uses these endpoints and runs on something like a cron job. However, it would make more sense to directly unload and load models as needed using management endpoints.

Closing this issue as out of scope.

**Comment by antonovkz** [comment]
> ### Problem
> 
> The model stays loaded onto VRAM, even after long time of idling. This causes higher Watt usage of the GPU and takes up VRAM that could be used by other programs.
> ### Solution
> 
> Add an auto unload on idle function. Possible options. IDLE_UNLOAD = true (enables / disables this feature) IDLE_TIME = 5m (sets the timeout timer) In this example, after 5 min of not receiving a request, the model gets unloaded. After receiving a new request while the model is unloaded. The model should be then loaded into VRAM again and the 5-min timer start's from the beginning.
> ### Alternatives
> 
> _No response_
> ### Explanation
> 
> Would reduce the electric bill on 24/7 operation :)
> ### Examples
> 
> https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-completion the keep_alive parameter on ollama
> ### Additional context
> 
> _No response_
> ### Acknowledgements
> 
>     * [x]  I have looked for similar requests before submitting this one.
> 
>     * [x]  I understand that the developers have lives and my issue will be answered when possible.
> 
>     * [x]  I understand the developers of this program are human, and I will make my requests politely.

Perhaps this is what you’re looking for. I’ve created a small Flask script implementing a proxy server to add the functionality I need for TabbyAPI:

Automatic Model Unloading:
If there are no requests to the server for a specified period (unload_timer), the model is automatically unloaded to free up resources.

Automatic Server Launch:
Upon receiving a request via the OpenAI API, the server automatically launches the model using the settings from the corresponding .yml configuration file.

Dynamic Model Switching:
If a request targets a different model, the currently loaded model is unloaded, and the new model is loaded automatically.

**Example config.yml File (located in the root folder alongside TabbyAPI):**
```
network:
  api_servers: ["OAI"]

model:
  model_dir: C:\Users\User\exl2  # General path for storing models
  inline_model_loading: false
  use_dummy_models: false
  tensor_parallel: false
  gpu_split_auto: false
  autosplit_reserve: [0]
  gpu_split: [25,25]
  rope_alpha: 1.0
```

The config/ folder should contain configuration files for each model. For example (./config/Qwen2.5-Coder-32B-Instruct-exl2-4bpw-hb8-65k.yml):
```
model:
  model_name: Qwen2.5-Coder-32B-Instruct-exl2-4.5bpw-hb8  # Folder name containing model weights in the shared directory
  cache_size: 32768
  max_seq_len: 32768
  cache_mode: Q4
  chunk_size: 1024
```
In this case, the model Qwen2.5-Coder-32B-Instruct-exl2-4bpw-hb8-65k will appear on the /v1/models endpoint via the proxy server, alongside all other models configured through the .yml files.


```
import os
import subprocess
import time
import threading
from flask import Flask, request, Response, stream_with_context, jsonify
import requests
import json
import logging
import sys

from flask_cors import CORS

app = Flask(__name__)
CORS(app)

debug_output = True

if debug_output:
    logging.basicConfig(level=logging.DEBUG)
else:
    logging.basicConfig(level=logging.INFO)

unload_timer = 30
api_endpoint = "http://127.0.0.1:5000"
config_dir = "config"

class ModelServer:
    def __init__(self):
        self.current_model = None
        self.current_process = None
        self.server_ready = False
        self.server_ready_event = threading.Event()
        self.last_access_time = None
        self.process_lock = threading.Lock()
        self.python_executable = sys.executable
        threading.Thread(target=self.check_last_access_time, daemon=True).start()

    def start_model_process(self, model):
        if self.current_process is not None:
            self.stop_model_process()
        
        global config_dir
        config_path = os.path.join(config_dir, f"{model}.yml")
        self.current_process = subprocess.Popen([self.python_executable, "start.py", "--config", config_path])
        logging.debug(f"Started process for model {model} with PID {self.current_process.pid}")
    
        self.server_ready = False
        threading.Thread(target=self.check_server_ready, args=()).start()
        self.last_access_time = time.time()
        return True

    def stop_model_process(self):
        if self.current_process is not None:
            self.current_process.terminate()
            self.current_process.wait()
            logging.debug(f"Stopped process with PID {self.current_process.pid}")
            self.current_process = None
            self.server_ready = False
            self.last_access_time = None
            self.current_model = None

    def check_server_ready(self):
        for _ in range(30):
            if self.is_server_ready():
                self.server_ready = True
                self.server_ready_event.set()
                logging.debug("Server is ready.")
                break
            time.sleep(1)
        else:
            logging.error("Server is not ready after 30 seconds. Terminating process.")
            self.stop_model_process()

    def is_server_ready(self):
        try:
            response = requests.get(f"{api_endpoint}/health", timeout=2)
            return response.status_code == 200
        except requests.exceptions.RequestException:
            return False

    def check_last_access_time(self):
        while True:
            if self.last_access_time is not None:
                elapsed_time = time.time() - self.last_access_time
                if elapsed_time > unload_timer:
                    logging.info(f"No requests for {elapsed_time} seconds. Stopping the model process.")
                    self.stop_model_process()
            time.sleep(5)

model_server = ModelServer()

@app.route('/v1/unload', methods=['GET'])
def unload():
    with model_server.process_lock:
        model_server.stop_model_process()
        logging.info(f"Stopping the model process.")
        response_data = { "status" : "success" }
    return jsonify(response_data)

@app.route('/v1/chat/completions', methods=['POST'])
def proxy():
    def generate():
        with model_server.process_lock:
            data = request.json
            logging.debug(json.dumps(data, ensure_ascii=False) + "\n")
            
            model = data.get('model')
            if model is not None and model_server.current_model != model:
                logging.info(f"Model changed from {model_server.current_model} to {model}")
                model_server.start_model_process(model)
                model_server.current_model = model
            
            for _ in range(60):
                if model_server.is_server_ready():
                    break
                time.sleep(1)
        
            if not model_server.is_server_ready():
                yield json.dumps({"error": "Server is not ready"}).encode('utf-8') + b"\n\n"
                return
            
            model_server.last_access_time = time.time()
                        
            try:
                with requests.post(f"{api_endpoint}/v1/chat/completions", json=data, stream=True) as resp:
                    for line in resp.iter_lines():
                        if line:
                            yield line + b"\n\n"
                            model_server.last_access_time = time.time()
                            logging.debug(f"{line}")
                    logging.debug("Finished streaming response")
                logging.debug("\n")
            except requests.exceptions.RequestException as e:
                logging.error(f"Request failed: {e}")
                yield f"error: {str(e)}\n\n"

    return Response(stream_with_context(generate()), content_type="text/event-stream")

@app.route('/v1/models', methods=['GET'])
def models():
    global config_dir
    model_files = [f for f in os.listdir(config_dir) if f.endswith('.yml')]
    model_ids = [os.path.splitext(f)[0] for f in model_files]
    
    response_data = {
        "object": "list",
        "data": [
            {
                "id": model_id,
                "object": "model",
                "owned_by": "tabbyAPI"
            }
            for model_id in model_ids
        ]
    }
    return jsonify(response_data)

if __name__ == '__main__':
    app.run(host='127.0.0.1', port=9000, debug=debug_output)
```

**Comment by rnett** [comment]
I don't think this is out of scope.  It's difficult to impossible to do outside of the server since we do not have usage info.  It's supported by other model apis like LM Studio, ollama, and llama-swap.
