### ISSUE TITLE
[REQUEST] Defered Type Hints & Type_checking paradigm

### ISSUE THREAD

**Issue by michaelfeil** [theroyallab/tabbyAPI#218]
### Problem

I saw the following pattern in your codebase!

Use: - https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING TYPE_CHECKING variable to only import type hints when needed.
And

defered type hints as forward reference: https://stackoverflow.com/questions/51629105/python-type-hint-given-as-a-string

    # Conditionally set the type hint based on importablity
    # TODO: Clean this up
    if dependencies.extras:
        engine: Optional[AsyncEmbeddingEngine] = None
    else:
        engine = None

### Solution

Above

### Explanation

Just fyi, send from mobile

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by bdashore3** [comment]
Fixed in aa4ccd03d4b84487200ab3f5288481b1cbbb8485

Not sure what StackOverflow means that runtime typing via strings is deprecated, but I'll keep it until it's gone.
