### ISSUE TITLE
[REQUEST] FlashAttention 1 Support.

### ISSUE THREAD

**Issue by Abdulhanan535** [theroyallab/tabbyAPI#221]
### Problem

Flashattention2 is not supported on Gpus like rtx 2080 or T4. FlashAttention 1 is suported.

### Solution

Implementation of FlashAttention 1.

### Alternatives

Nothing only tabbyapi.

### Explanation

Flashattention2 is not supported on Gpus like rtx 2080 or T4. FlashAttention 1 is suported. It can increase speed.

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by turboderp** [comment]
The first fallback when flash-attn isn't available is Torch SDPA, which will use Torch's own implementation of Flash Attention if possible.

Generally speaking, the original flash-attn performed poorly at small batch sizes, and it lacks lower-right causal masking which makes it a non-starter anyway.

**Comment by Abdulhanan535** [comment]
okay. Thanks.
