### ISSUE TITLE
[REQUEST] Fix the links on the landing page of the wiki

### ISSUE THREAD

**Issue by Feldherren** [theroyallab/tabbyAPI#227]
### Problem

All internal wiki links on the wiki landing page (https://github.com/theroyallab/tabbyAPI/wiki/) produce a 'You do not have permission to update this wiki.' error. This only applies to the internal wiki links in the page's text, not the contents table links on the right-hand sidebar, or the link to the autogenerated documentation.

### Solution

The links in the text should... take you to the page they're presumably intended to point at.
Taking a look at the Getting Started link, it seems that it's attempting to create a new page because the link in text doesn't have the leading zero. All the other internal links are similar.

### Alternatives

The table of contents works for navigation, so the wiki isn't completely inaccessible.

### Explanation

Whilst there's a workaround, users may simply assume the wiki is unfinished and the pages do not exist, faced with this error. 
Also, it's hopefully a quick fix.

### Examples

Link in text to Getting Started page: https://github.com/theroyallab/tabbyAPI/wiki/1.-Getting-Started (does not work)
Link in ToC to Getting Started page: https://github.com/theroyallab/tabbyAPI/wiki/01.-Getting-Started (works)

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by bdashore3** [comment]
Should be fixed. Thanks!
