### ISSUE TITLE
[REQUEST] Vision support.

### ISSUE THREAD

**Issue by Ph0rk0z** [theroyallab/tabbyAPI#229]
### Problem

Tabby API currently only handles text. Many vision models have released. Exllama dev supports qwen2-vl

### Solution

Support vision through openAI api. Hopefully in text completion too.

### Explanation

More multi-modal models will be created over time. Would be cool to have a fully integrated experience. i.e Creating an image with a model and having it iteratively use the image gen tool after seeing what it got back.

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by bdashore3** [comment]
I understand the excitement over vision models and would like to implement support once there's a proper pipeline on how to do so via exllamav2.

According to turbo, the current dev branch is experimental and only works with the _image_ part of llava. There still needs to be support for Qwen-2 VL and other models which is most likely being worked on at this time:

I'd keep an eye on this issue https://github.com/turboderp/exllamav2/issues/658 for the time being as that's a blocking issue.
> It should work for Qwen2-VL as well, although that will require some updates to the RoPE since they have multidimensional positional embeddings for images. Even a time dimension for video, just to make it that much harder. :P

**Comment by bdashore3** [comment]
Closing since tracking issue #235 is open
