### ISSUE TITLE
[REQUEST] Vision Models

### ISSUE THREAD

**Issue by bdashore3** [theroyallab/tabbyAPI#235]
### Problem

Tracking issue for getting vision models working, supersedes #229.

TImeline:
- [x] Add support for loading vision tower
- [ ] Accept image objects in chat completions
- [ ] Parse and insert images in exl2 backend (base64 -> Pillow)
- [ ] Handle images in chat templates

### Solution

Contributions are welcome here as I am not sure how vision prompting works in the first place and that'll require research and a lot of time.

Please PR to the [vision](https://github.com/theroyallab/tabbyAPI/tree/vision) branch

### Explanation

Tracking issue

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by Ph0rk0z** [comment]
Can I request text completion vision support too? Chat completion is much more difficult to control.

**Comment by bdashore3** [comment]
Code-wise, text completion with vision is not possible since chat completion separates images and text into defined payloads with roles. If there's examples proving otherwise, I can look into it.

**Comment by turboderp** [comment]
This should be possible in theory, since images in Llava-style models are inserted into the context as essentially tokens, and the way it's implemented in ExLlama is flexible enough to allow it. All it would need is an extension to the completion API to accept images with a placeholder text for each image.

But I don't think there are any vision models trained on image inputs outside the context of instruct tuning. So I wouldn't expect reliable results.

**Comment by DocShotgun** [comment]
Looking at implementing the vision support right now. It's definitely theoretically possible to implement exllamav2 vision on the text completion endpoint, but I'm not aware of any API standard defining how to format such things.

If you had some kind of standardized string that specifies an image URL or base64 image in the prompt, in theory we could find all of those, create embedding/text alias pairs, and feed them into the generator the same way as a formatted chat completion prompt.

**Comment by bdashore3** [comment]
This has been completed as of the most recent commits. Text completion will be thought about on a later date.

**Comment by mammour** [comment]
https://huggingface.co/spaces/pandora-s/Pixtral-12B-EXL2/blob/main/app.py

seems like Pandora showed us the way for text-completion :)
