### ISSUE TITLE
[BUG] 2 concurrent requests make both stream.. FASTER than single stream? Exllamav2 issue or?

### ISSUE THREAD

**Issue by Originalimoc** [theroyallab/tabbyAPI#247]
### OS

WSL2

### GPU Library

CUDA 12.x

### Python version

3.11

### Describe the bug

When loading a model close to max out VRAM. Single request get 3tk/s. While you request another one, both speed goes to 10tk/s. You cancel one while generating, then the alive one will drop to ~3tk/s again.

### Reproduction steps

Use a model and cache configuration that can almost max out the VRAM, then do a 2 concurrent requests to chat completion API with same request.

### Expected behavior

Single stream/total speed ~= 20tk/s. It's the speed when you reduce some cache size.

### Logs

Later I'll get you a live bug video.

### Additional context

Not sure if this is Exllamav2 behavior or..?

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by DocShotgun** [comment]
> When loading a model close to max out VRAM. Single request get 3tk/s.

> Single stream/total speed ~= 20tk/s. It's the speed when you reduce some cache size.

This sounds like what happens when you hit sysmem fallback and part of your VRAM contents are offloaded to RAM, but I'm not sure if that's even supported in WSL lol. I've gotten very close to OOM with my cache size - like allocating one more page of 256 tokens results in OOM on load- and not had this issue (in native Linux), so I'm not sure what would be the cause here.

**Comment by bdashore3** [comment]
This is not a code-related bug, but rather a support request. Please use the [Discord](https://discord.gg/sYQxnuD7Fj) for those.

**Comment by Originalimoc** [comment]
@DocShotgun
The "shared GPU mem" is accessible by CUDA in WSL. It won't OOM until shared(it allocated half system main RAM) + dedicated VRAM are all full. And no, given VRAM Ultilization not "leaking" to shared RAM + Core Ultilization at ~100%(it will drop to < 50% and jump around if swap happens) in task manager + HWInfo RAM RW speed I'm pretty sure I didn't hit the "swapping point" yet and system is fully responsive and all main ops are inside GPU.

And after all, the main problem is, why TWO requests is significantly faster/correct speed than, ONE...?

**Comment by Originalimoc** [comment]
@bdashore3 it is. but my guess is it is a lower level issue maybe in driver or CUDA kernel than API fronend issue, just as in issue title
