### ISSUE TITLE
[BUG] "Disabling GPU split because one GPU is in use" - then Tabby only uses 1 GPU

### ISSUE THREAD

**Issue by sammcj** [theroyallab/tabbyAPI#250]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.12

### Describe the bug

Just recently Tabby has been failing to use both my GPUs (2x 3090), this previously worked fine
It also seems that Tensor parallel has stopped working.

In the logs I see:

```
INFO:     172.22.0.3:57812 - "POST /v1/model/load HTTP/1.1" 200
INFO:     Disabling GPU split because one GPU is in use.
INFO:     Attempting to load a prompt template if present.
INFO:     Using template "qwen2.5-toolcalling-experimental" for chat
completions.
INFO:     Loading model: /app/models/bartowski_Qwen2.5-Coder-32B-Instruct-exl2
INFO:     Loading with a manual GPU split (or a one GPU setup)
Loading model modules ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 131/131 0:00:00
```

Then it fails to load the model as it's run out of vRAM - despite not using any of the 24GB on the second card.

- No other processes are running on either cards
- The cards both provided to the container in the same way
- Both cards work fine with Ollama/llama.cpp

### Reproduction steps

- Run the official Docker container
- Try to load a model with gpu_split_auto: true (via Tabby Gradio Loader)
- Note that Tabby only uses 1 out of your 2 GPUs
- Note that tensor parallel doesn't seem to work, inference only occurs on 1 gpu

### Expected behavior

The majority of the model to be loaded on the first card, then any remaining layers loaded on the second card.

### Logs

INFO     2024-11-23 05:31:50,960 datasets INFO: PyTorch version     config.py:54
         2.4.1+cu121 available.
INFO:     ExllamaV2 version: 0.2.4
WARNING:  EXPERIMENTAL: Enabled the pytorch CUDA malloc backend.
WARNING:  EXPERIMENTAL: Running program with Uvloop/Winloop.
WARNING:  EXPERIMENTAL: Process priority set to Realtime.
WARNING:  If you're not running on administrator/sudo, the priority is set to
high.
INFO:     Your API key is: redacted
INFO:     Your admin key is: redacted
INFO:
INFO:     If these keys get compromised, make sure to delete api_tokens.yml and
restart the server. Have fun!
INFO:     Generation logging is disabled
INFO:     Developer documentation: http://0.0.0.0:5000/redoc
INFO:     Starting OAI API
INFO:     Completions: http://0.0.0.0:5000/v1/completions
INFO:     Chat completions: http://0.0.0.0:5000/v1/chat/completions
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
INFO:     172.22.0.3:60608 - "GET /v1/auth/permission HTTP/1.1" 200
INFO:     172.22.0.3:60608 - "GET /v1/model/list HTTP/1.1" 200
INFO:     172.22.0.3:60608 - "GET /v1/model/draft/list HTTP/1.1" 200
INFO:     172.22.0.3:60608 - "GET /v1/lora/list HTTP/1.1" 200
INFO:     172.22.0.3:60608 - "GET /v1/template/list HTTP/1.1" 200
INFO:     172.22.0.3:60608 - "GET /v1/sampling/override/list HTTP/1.1" 200
ERROR:    Sent to request: No models are currently loaded.
INFO:     172.22.0.3:60608 - "GET /v1/model HTTP/1.1" 400
ERROR:    Sent to request: No models are currently loaded.
INFO:     172.22.0.3:60608 - "GET /v1/lora HTTP/1.1" 400
ERROR:    Sent to request: No models are currently loaded.
INFO:     172.22.0.3:36694 - "POST /v1/model/unload HTTP/1.1" 400
INFO:     172.22.0.3:36694 - "POST /v1/model/load HTTP/1.1" 200
INFO:     Disabling GPU split because one GPU is in use.
INFO:     Attempting to load a prompt template if present.
INFO:     Using template "qwen2.5-toolcalling-experimental" for chat
completions.
INFO:     Loading model: /app/models/bartowski_Qwen2.5-Coder-32B-Instruct-exl2
INFO:     Loading with a manual GPU split (or a one GPU setup)
Loading model modules ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 131/131 0:00:00
ERROR:    Traceback (most recent call last):
ERROR:      File "/app/endpoints/core/utils/model.py", line 120, in
stream_model_load
ERROR:        async for module, modules, model_type in load_status:
ERROR:      File "/app/common/model.py", line 90, in load_model_gen
ERROR:        async for module, modules in load_status:
ERROR:      File "/app/backends/exllamav2/model.py", line 562, in load_gen
ERROR:        async for value in iterate_in_threadpool(model_load_generator):
ERROR:      File "/app/common/concurrency.py", line 30, in iterate_in_threadpool
ERROR:        yield await asyncio.to_thread(gen_next, generator)
ERROR:      File "/usr/lib/python3.10/asyncio/threads.py", line 25, in to_thread
ERROR:        return await loop.run_in_executor(None, func_call)
ERROR:      File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in
run
ERROR:        result = self.fn(*self.args, **self.kwargs)
ERROR:      File "/app/common/concurrency.py", line 20, in gen_next
ERROR:        return next(generator)
ERROR:      File
"/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 57,
in generator_context
ERROR:        response = gen.send(request)
ERROR:      File "/app/backends/exllamav2/model.py", line 679, in
load_model_sync
ERROR:        self.cache = self.create_cache(
ERROR:      File "/app/backends/exllamav2/model.py", line 734, in create_cache
ERROR:        return cache_class(
ERROR:      File "/usr/local/lib/python3.10/dist-packages/exllamav2/cache.py",
line 596, in __init__
ERROR:        super().__init__(
ERROR:      File "/usr/local/lib/python3.10/dist-packages/exllamav2/cache.py",
line 441, in __init__
ERROR:        self.create_state_tensors(copy_from, lazy)
ERROR:      File "/usr/local/lib/python3.10/dist-packages/exllamav2/cache.py",
line 92, in create_state_tensors
ERROR:        p_value_states = torch.zeros(self.shape_wv, dtype = self.dtype,
device = device).contiguous()
ERROR:    torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00
MiB. GPU 0 has a total capacity of 23.80 GiB of which 35.12 MiB is free. Process
2332205 has 23.76 GiB memory in use. Of the allocated memory 23.43 GiB is
allocated by PyTorch, and 19.27 MiB is reserved by PyTorch but unallocated. If
reserved but unallocated memory is large try setting
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See
documentation for Memory Management
(https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
ERROR:    Sent to request: CUDA out of memory. Tried to allocate 32.00 MiB. GPU
0 has a total capacity of 23.80 GiB of which 35.12 MiB is free. Process 2332205
has 23.76 GiB memory in use. Of the allocated memory 23.43 GiB is allocated by
PyTorch, and 19.27 MiB is reserved by PyTorch but unallocated. If reserved but
unallocated memory is large try setting
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See
documentation for Memory Management
(https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
ERROR:    Sent to request: No models are currently loaded.
INFO:     172.22.0.3:36694 - "GET /v1/model HTTP/1.1" 400
ERROR:    Sent to request: No models are currently loaded.
INFO:     172.22.0.3:36694 - "GET /v1/lora HTTP/1.1" 400
ERROR:    Sent to request: No models are currently loaded.
INFO:     172.22.0.3:45114 - "POST /v1/model/unload HTTP/1.1" 400
INFO:     172.22.0.3:45114 - "POST /v1/model/load HTTP/1.1" 200
INFO:     Unloading existing model.
INFO:     Model unloaded.
INFO:     Disabling GPU split because one GPU is in use.
INFO:     Attempting to load a prompt template if present.
INFO:     Using template "qwen2.5-toolcalling-experimental" for chat
completions.
INFO:     Loading model: /app/models/bartowski_Qwen2.5-Coder-32B-Instruct-exl2
INFO:     Loading with a manual GPU split (or a one GPU setup)
Loading model modules ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 131/131 0:00:00
ERROR:    Traceback (most recent call last):
ERROR:      File "/app/endpoints/core/utils/model.py", line 120, in
stream_model_load
ERROR:        async for module, modules, model_type in load_status:
ERROR:      File "/app/common/model.py", line 90, in load_model_gen
ERROR:        async for module, modules in load_status:
ERROR:      File "/app/backends/exllamav2/model.py", line 562, in load_gen
ERROR:        async for value in iterate_in_threadpool(model_load_generator):
ERROR:      File "/app/common/concurrency.py", line 30, in iterate_in_threadpool
ERROR:        yield await asyncio.to_thread(gen_next, generator)
ERROR:      File "/usr/lib/python3.10/asyncio/threads.py", line 25, in to_thread
ERROR:        return await loop.run_in_executor(None, func_call)
ERROR:      File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in
run
ERROR:        result = self.fn(*self.args, **self.kwargs)
ERROR:      File "/app/common/concurrency.py", line 20, in gen_next
ERROR:        return next(generator)
ERROR:      File
"/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 57,
in generator_context
ERROR:        response = gen.send(request)
ERROR:      File "/app/backends/exllamav2/model.py", line 679, in
load_model_sync
ERROR:        self.cache = self.create_cache(
ERROR:      File "/app/backends/exllamav2/model.py", line 734, in create_cache
ERROR:        return cache_class(
ERROR:      File "/usr/local/lib/python3.10/dist-packages/exllamav2/cache.py",
line 596, in __init__
ERROR:        super().__init__(
ERROR:      File "/usr/local/lib/python3.10/dist-packages/exllamav2/cache.py",
line 441, in __init__
ERROR:        self.create_state_tensors(copy_from, lazy)
ERROR:      File "/usr/local/lib/python3.10/dist-packages/exllamav2/cache.py",
line 95, in create_state_tensors
ERROR:        p_value_scales = torch.zeros(self.shape_s, dtype = torch.float16,
device = device).contiguous()
ERROR:    torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00
MiB. GPU 0 has a total capacity of 23.80 GiB of which 15.12 MiB is free. Process
2332205 has 23.78 GiB memory in use. Of the allocated memory 23.47 GiB is
allocated by PyTorch, and 3.27 MiB is reserved by PyTorch but unallocated. If
reserved but unallocated memory is large try setting
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See
documentation for Memory Management
(https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
ERROR:    Sent to request: CUDA out of memory. Tried to allocate 20.00 MiB. GPU
0 has a total capacity of 23.80 GiB of which 15.12 MiB is free. Process 2332205
has 23.78 GiB memory in use. Of the allocated memory 23.47 GiB is allocated by
PyTorch, and 3.27 MiB is reserved by PyTorch but unallocated. If reserved but
unallocated memory is large try setting
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See
documentation for Memory Management
(https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
ERROR:    Sent to request: No models are currently loaded.
INFO:     172.22.0.3:45114 - "GET /v1/model HTTP/1.1" 400
ERROR:    Sent to request: No models are currently loaded.
INFO:     172.22.0.3:45114 - "GET /v1/lora HTTP/1.1" 400

### Additional context

```
root@tabby:/app# nvidia-smi
Sat Nov 23 05:35:41 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.01              Driver Version: 565.57.01      CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        On  |   00000000:01:00.0 Off |                  N/A |
| 32%   40C    P8             12W /  310W |       4MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 3090        On  |   00000000:16:00.0 Off |                  N/A |
| 30%   32C    P8             22W /  290W |       4MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by bdashore3** [comment]
This seems to be a user issue related to Docker configuration. Tabby uses `torch.cuda.device_count()` to get the number of GPUs on a system. If it's not responding properly, then I'd open up a REPL inside your container and run:

```python
import torch
print(torch.cuda.device_count())
```

I'm not a docker expert though, the [Discord](https://discord.gg/sYQxnuD7Fj) seems like a better place for this problem.

**Comment by sammcj** [comment]
```
docker exec -it tabby /bin/bash

root@tabby:/app# nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 3090 (UUID: GPU-1d22e49d-3fa7-3a05-319b-f7350971c710)
GPU 1: NVIDIA GeForce RTX 3090 (UUID: GPU-875d550c-606a-9920-3296-7b219227b718)

root@tabby:/app# python3
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.cuda.device_count())
1
```

Two interesting things here:

1. Indeed PyTorch is only seeing 1 GPU despite 2 GPUs being present in the container.
2. The TabbyAPI container seems to be running old EOL Python version (3.10.x)

---

Re: 1 - Out of interest - What about the configuration makes you think it's Docker related?

As mentioned - Ollama/llama.cpp/TextgenWebUI etc.. and all my other Docker GPU containers are working fine with both GPUs, I actually have about 20 GPU-enabled containers running at present the only one that is seeing just 1 GPU is the TabbyAPI container.

This is the standard pattern I use for all GPU enabled containers, TabbyAPI included (only if you're interested):

```yaml
services:
  &name tabby:
    container_name: *name
    hostname: *name
    ipc: host
    build:
      context: https://github.com/theroyallab/tabbyAPI.git#main
      dockerfile: docker/Dockerfile
      args:
        DO_PULL: true
        TORCH_CUDA_ARCH_LIST: "8.6;8.6+PTX"
        CMAKE_CUDA_ARCHITECTURES: "sm_86"
    environment:
      NAME: tabby
      NVIDIA_VISIBLE_DEVICES: all
      TORCH_CUDA_ARCH_LIST: "8.6;8.6+PTX"
      CMAKE_CUDA_ARCHITECTURES: "sm_86"
      CUDA_DEVICE_ORDER: FASTEST_FIRST
    volumes:
      - /mnt/llm/models/exl2:/usr/src/app/models
      - /mnt/llm/models/exl2:/app/models
      - /mnt/llm/models/exl2/loras:/app/loras
      - /mnt/llm/models/modelfiles/TabbyAPI/templates:/app/templates
      - /mnt/llm/models/modelfiles/TabbyAPI/sampler_overrides:/app/sampler_overrides
      - /mnt/llm/models/modelfiles/TabbyAPI/templates:/usr/src/app/templates
      - ./tabbyapi/config.yml:/app/config.yml
      - ./tabbyapi/api_tokens.yml:/app/api_tokens.yml
      - ./tabbyapi/config.yml:/usr/src/app/config.yml
      - ./tabbyapi/presets:/app/presets
  devices:
    - /dev/nvidia0:/dev/nvidia0
    - /dev/nvidia1:/dev/nvidia1
  runtime: nvidia
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            capabilities: [ "compute", "utility", "graphics" ]
            count: all
          - driver: cdi
            device_ids:
              - nvidia.com/gpu=all
            capabilities: [ "compute", "utility", "graphics" ]
```

---

Re: 2 - 3.10 was [EOL around a year and a half ago](https://endoflife.date/python).
I think that version of Python is coming from the [Nvidia base image which uses CUDA 12.1](https://github.com/theroyallab/tabbyAPI/blob/main/docker/Dockerfile#L2) - which is also EOL  (current stable is 12.6.2).

I'm not sure if perhaps there's a bug in these older Python/CUDA versions, or perhaps when they're that far behind the nvidia driver version - or if it's just completely unrelated.

Either way - I'd be happy to submit a PR to update these if you'd find that helpful in general?

**Comment by sammcj** [comment]
Just after replying with ^ I just found something interesting - it seems the Python/Torch version Tabby is using is misbehaving when `NVIDIA_VISIBLE_DEVICES` is set to `all`!

If you manually specify the GPUs by UUID, torch sees both!

```
CUDA_VISIBLE_DEVICES: "GPU-1d22e49d-3fa7-3a05-319b-f7350971c710,GPU-875d550c-606a-9920-3296-7b219227b718"
```

```
root@tabby:/app# python3
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.cuda.device_count())
2
```

This is a usable workaround for the issue, but I would still suggest updating to current Python and CUDA container image versions.
