### ISSUE TITLE
[REQUEST] Auto switch draft model on and off according to context length(prompt + completion).

### ISSUE THREAD

**Issue by Originalimoc** [theroyallab/tabbyAPI#255]
### Problem

You now need to choose either 16k context + 50~60tk/s with drafting or 32k context without drafting with ~30tk/s.

### Solution

For users most of time short context and occasionally long context, auto reload when too long without draft config is very worth the tradeoff.

### Alternatives

hard link two model directory but with two tabby_config.yml file, manually choosing.

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by DocShotgun** [comment]
This sounds problematic if there are multiple users sending requests of different context lengths, potentially causing a lot of unloading/reloading.

**Comment by bdashore3** [comment]
Agreed. This doesn't really seem like something that should be in Tabby. However, loading/unloading is supported via the API, so this can be done via the client or something in front of tabby.

Closing this issue.
