### ISSUE TITLE
[BUG] OAI doc recommends parameter max_completion_tokens over max_tokens. Support aloneside with max_tokens.

### ISSUE THREAD

**Issue by Originalimoc** [theroyallab/tabbyAPI#256]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.12

### Describe the bug

Some client already switched to max_completion_tokens.
Fixed by common\sampling.py:28 to "validation_alias=AliasChoices("max_tokens", "max_length", "max_completion_tokens"),"

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by bdashore3** [comment]
Closed in c23e406f2db6451184787b3bbe39daf0102d1d66
