### ISSUE TITLE
[BUG] json_schema not always enforced

### ISSUE THREAD

**Issue by afoland** [theroyallab/tabbyAPI#258]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.10

### Describe the bug

When passing in a very simple  json_schema (as a pydantic_model.schema() derived from a JSON schema string), the response conforms to the schema only about 75% of the time.  

25% of the time generation fails to conform.  This is split between about 15% where only one of the two required keys is in the response; about 10% where the final closing bracket "}" is missing, and a low rate of messages returning only "{}"

### Reproduction steps

I pass in a 2-element json schema to the api call payload using 

> payload["json_schema"]=pydantic_model.schema()

The JSON schema is very simple (designed to give {"country":"COUNTRY_NAME", "capital","CAPITAL_NAME"):

>     {'$schema': 'http://json-schema.org/draft-07/schema#',
>      'type': 'object',
>      'properties': {'country': {'type': 'string', 'maxLength': 30},
>                     'capital': {'type': 'string', 'maxLength': 30}},
>      'required': ['country', 'capital'],
>      'additionalProperties': False}

I made a chat completions call asking for the capital of France.

The chat_completions call works as expected (generating a chatty paragraph about Paris) when the json_schema is not set.

### Expected behavior

I expected a response looking like

{"country":"France","capital":"Paris"}

This actually works 75% of the time.  

Note that I did not put anything in the system message or prompt to tell it to return a json.  (If I do that, return is 100% successful even without setting json_schema).

### Logs

Validation Error: 'country' is a required property

Failed validating 'required' in schema:
    {'$schema': 'http://json-schema.org/draft-07/schema#',
     'type': 'object',
     'properties': {'country': {'type': 'string', 'maxLength': 30},
                    'capital': {'type': 'string', 'maxLength': 30}},
     'required': ['country', 'capital'],
     'additionalProperties': False}

On instance:
    {'capital': 'Paris'}
AI: {"capital":"Paris"}

### Additional context

I put code to reproduce this in [a github repo](https://github.com/afoland/tabbyAPItesting)--look at the json_validation (and capital_json_schema.txt)

(Also, the github repo has a very simple example python for calling tabbyAPI)

Possibly related to [issue #131](https://github.com/theroyallab/tabbyAPI/issues/131), which seems to indict LMFE

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by DocShotgun** [comment]
Not going to be looked at because the entire constrained generation backend is being overhauled.

**Comment by afoland** [comment]
Sensible--happy to try some test cases once overhaul is there

**Comment by DocShotgun** [comment]
@afoland The latest tabbyAPI now has the Formatron backend, which should support the `required` field.

**Comment by bdashore3** [comment]
Merged the formatron PR that @DocShotgun had open and tested your JSON schema from this issue. It did work as asked. Remember, if the schema doesn't come out exactly right, you may need to prompt the model to do so.

Please update your dependencies to use Formatron.

Closing this issue as the test case is now passing.
