### ISSUE TITLE
[BUG] Skyfall/Tunguska models do not work in SillyTavern

### ISSUE THREAD

**Issue by frenzybiscuit** [theroyallab/tabbyAPI#263]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.11

### Describe the bug

When using SillyTavern with Skyfall & Tunguska models, TabbyAPI produces errors in chat completion mode.

They -do- work in open webui.

This is my first time making exl2 quants, so maybe im doing something wrong.

https://huggingface.co/FrenzyBiscuit/Skyfall-39B-v1-5.0bpw-h6-exl2

![Screenshot From 2024-12-16 10-37-57](https://github.com/user-attachments/assets/9ea33bcf-7bb9-4db1-890b-bdfac2753cc5)

### Reproduction steps

Install skyfall exl2

Install st

Use st chat completion with open-webui as the frontend/backend & tabbyAPI for the llm server.

### Expected behavior

works

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by DocShotgun** [comment]
The error message explains this.

`After the optional system message, conversation roles must alternate user/assistant/user/assistant/...`

This is a model that has a strict chat template that enforces the turn order of (system)/user/assistant/user/assistant/etc., and apparently however you have ST configured for chat completion mode does not adhere to this, while openwebui does. ST user myself here - why not just use text completion mode?

**Comment by DocShotgun** [comment]
I would recommend using text completion mode in SillyTavern connecting directly to TabbyAPI.

If for some reason you cannot, I'd try enabling this highlighted option in SillyTavern:
![image](https://github.com/user-attachments/assets/00356ebc-f7b3-4519-b3b3-28f84dc810fc)

**Comment by DocShotgun** [comment]
It's not an error in the config per se. It's just an aggressively strict chat template. Again though, I don't quite understand why you'd want to route your ST requests through open-webui API to TabbyAPI when TabbyAPI is directly supported as a backend by ST.
