### ISSUE TITLE
[REQUEST] Consider making this Apache/MIT License?

### ISSUE THREAD

**Issue by rjmehta1993** [theroyallab/tabbyAPI#267]
### Problem

AGPL license, though commercial but it is not friendly. The best and easiest is Apache/MIT for commercial use. 

### Solution

Make this Apache2.0 or MIT

### Explanation

AGPL license, though commercial but it is not friendly. The best and easiest is Apache/MIT for commercial use. 

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by bdashore3** [comment]
Due to TabbyAPI's nature as a hobbyist project, I prefer to preserve the open source spirit and keep it as AGPL.
