### ISSUE TITLE
Samplers

### ISSUE THREAD

**Issue by bdashore3** [theroyallab/tabbyAPI#3]
Exllamav2 (the backend for TabbyAPI) supports a lot of samplers already, but we still have a few more to iron out.

To add samplers, please look into [exllamav2's source](https://github.com/turboderp/exllamav2) and then the `model.py` file in TabbyAPI to interface with the new samplers.

Undecided:
- Grammar? (there's many implementations to choose from)

Added, but not in exllamav2 stable:
- CFG - Added in b378773d0a8729270845523bee63f4663892aac2
- Top A - Added in 80ef3797216e62c7b7bca1f7b356decd83fb3769
- Freq pen - Added in e256ff8182546ab628ce033ba0c1115ae29d8991
- Presence pen - Added in e256ff8182546ab628ce033ba0c1115ae29d8991

NOTES:
- Freq pen is currently redirected to rep pen.
- Priority is relative, but this is what should be implemented first, next, etc...
- Sampling order has been implemented as temperature_last

**Comment by Cloudwalker2k3** [comment]
Could you possible add Noisy Sample and Min_P as shown in Kalomaze's Kobold CPP? These may work great with Exllama2.

**Comment by bdashore3** [comment]
Logit bias added in c3f78989673b638a5c0b7c0821e765b402cad178

**Comment by AlpinDale** [comment]
Top-A is now merged. Frequency/Repetition is a WIP at [#241](https://github.com/turboderp/exllamav2/pull/241)

**Comment by bdashore3** [comment]
CFG added in b378773d0a8729270845523bee63f4663892aac2

**Comment by bdashore3** [comment]
This issue can be considered as complete now with the exception of grammar. Currently waiting on an exllamav2 stable release to close this issue.

**Comment by bdashore3** [comment]
The sampler backlog has been completed as of exllama v0.0.12. Closing this issue.
