### ISSUE TITLE
Small issue with Pydantic V2

### ISSUE THREAD

**Issue by Nodice** [theroyallab/tabbyAPI#32]
After getting the latest I received an import error from Pydantic. I saw the comment about the switch to Pydantic 2.

Doing a "pip install -U pydantic" Resolved it. 

Might be good to add the "-U" to the requirements.txt

**Comment by bdashore3** [comment]
Did you run `pip install --upgrade  -r requirements.txt` as stated in the `Updating` section of the README?

**Comment by bdashore3** [comment]
I've added a pin to pydantic 2.0 in the latest requirements update, so running `pip install -r requirements.txt` will force 2.x. Closing this issue.
