### ISSUE TITLE
NumExperts is ignored?

### ISSUE THREAD

**Issue by Ph0rk0z** [theroyallab/tabbyAPI#42]
In sillytavern console it says null for num experts. Inference performs as if only 2 experts were used despite an override being set. I did num experts: value like for any others.

**Comment by bdashore3** [comment]
Fixed in 3622710582a8c286b6df6e402dfd279114a668ef. The reporting wasn't hooked properly.

Ideally, you shouldn't be overriding the `num_experts_per_token` property. Exllamav2 sets it for you based on the model config. As stated in the `config_sample.yml`

```
# WARNING: Don't set this unless you know what you're doing!
```
