### ISSUE TITLE
seed

### ISSUE THREAD

**Issue by palacinka** [theroyallab/tabbyAPI#48]
hello, why is seed commented out in common.py?
https://github.com/theroyallab/tabbyAPI/blob/main/OAI/types/common.py#L51C7-L51C11

I am trying to generate unique variations of same prompt with exllamav2 and I thought seed is required for that.

**Comment by turboderp** [comment]
A seed isn't required to get unique generations from one prompt. It would be required to get the same response over and over, but even then ExLlamaV2 isn't entirely deterministic.

**Comment by palacinka** [comment]
My bad. Thank you for clarification. I am learning.
May I ask would changing seed help me to get more variants of content generated on low temperature?  I like the style of content written on low temperature  and I am looking for ways to introduce variants into it.

**Comment by bdashore3** [comment]
Seed will do the opposite of what you're asking for here. I'd advise looking into various samplers and seeing how they change things as they randomize outputs.

A good combo to start out with is min-p = 0.05, temperature 1.5, and repetition penalty at 1.05.

In addition, this type of issue isn't in the scope of this repo. I'd advise joining a discord server for frontends such as [SillyTavern](https://github.com/sillytavern/sillytavern#we-now-have-a-community-discord-server) and asking about sampling there.

Closing this issue.
