### ISSUE TITLE
error when loading start.bat

### ISSUE THREAD

**Issue by deathtome1998** [theroyallab/tabbyAPI#60]
when I load start.bat in the venv I get a traceback everytime. the two most recent ones have said things about ExLlamaV2TokenizerHF(path_hf). and an assertion error that says attempting to load HF tokenizer, but Tokenizers library is not installed. I don't see anything in the install instructions about a Tokenizers library. if someone knows what's going on I'd appreciate help fixing it.

**Comment by DocShotgun** [comment]
Are you trying to use a deepseek model?

**Comment by deathtome1998** [comment]
not sure? I'm using [brucethemoose][Yi-34B-200K-DARE-megamerge-v8] as my model.

**Comment by DocShotgun** [comment]
Not sure on that one, only Deepseek should require the tokenizers library. But that's some funky merge and who knows what was done to it. What's the exact repo for the model you're trying to load, presumably some quantized version?

**Comment by bdashore3** [comment]
Agreed, please send a traceback that reflects what happened.

**Comment by deathtome1998** [comment]
here's the traceback from the console.
Traceback (most recent call last):
  File "B:\local-ai-chat\_tabbyapi\tabbyAPI\start.py", line 69, in <module>
    entrypoint(convert_args_to_dict(args, parser))
  File "B:\local-ai-chat\_tabbyapi\tabbyAPI\main.py", line 639, in entrypoint
    for module, modules in load_status:
  File "B:\local-ai-chat\_tabbyapi\tabbyAPI\backends\exllamav2\model.py", line 329, in load_gen
    self.tokenizer = ExLlamaV2Tokenizer(self.config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\local-ai-chat\_tabbyapi\tabbyAPI\venv\Lib\site-packages\exllamav2\tokenizer.py", line 66, in __init__
    elif os.path.exists(path_hf): self.tokenizer = ExLlamaV2TokenizerHF(path_hf)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\local-ai-chat\_tabbyapi\tabbyAPI\venv\Lib\site-packages\exllamav2\tokenizers\hf.py", line 20, in __init__
    assert self.is_supported(), "Attempting to load HF tokenizer, but Tokenizers library is not installed"
AssertionError: Attempting to load HF tokenizer, but Tokenizers library is not installed 

as for how to find the exact repo for the model I'm not sure how to do that. I just grabbed the only version of the files that was on that page for that model at https://huggingface.co/brucethemoose/Yi-34B-200K-DARE-megamerge-v8/tree/main. although I did have to manually download the safetensors files because for some reason git clone wasn't downloading them for me. so I don't know if that has anything to do with it.

**Comment by bdashore3** [comment]
I believe the model creator messed something up when publishing the FP16. Yi has a tokenizer.model file that's supported by exllamav2. Therefore, there are two ways to fix this problem:

1. Download tokenizer.model from [the base model](https://huggingface.co/01-ai/Yi-34B-200K/tree/main). Also raise an issue on that huggingface repo if this tokenizer works.
2. Install the `tokenizers` library in your venv. To do this, run `.\venv\Scripts\activate` inside your tabby folder, then run `pip install tokenizers`. Afterwards, restart tabby and it should launch.

If you'd like more help, please join the [Discord server](https://discord.gg/sYQxnuD7Fj) as it's more relevant for support questions. Closing this issue.
