### ISSUE TITLE
[REQUEST] Add grammar support

### ISSUE THREAD

**Issue by c608345** [theroyallab/tabbyAPI#68]
**Is your feature request related to a problem? Please describe.**
Grammar makes llm output predictable.

**Describe the solution you'd like**
Support outlines https://github.com/outlines-dev/outlines

**Why should this feature be added?**
Grammar is a usefull feature.

**Comment by bdashore3** [comment]
Please look at [This branch](https://github.com/theroyallab/tabbyAPI/tree/json-grammar) as a tracking feature.

**Comment by bdashore3** [comment]
Grammar in the form of outlines EBNF and lm-format-enforcer JSON schemas have been added into the main branch. I highly recommend using JSON schemas when possible since outlines is slow. Closing this issue, but we'll add our own in-house implementation in the future.
