### ISSUE TITLE
[REQUEST] Embeddings support

### ISSUE THREAD

**Issue by acrylicode** [theroyallab/tabbyAPI#69]
**Is your feature request related to a problem? Please describe.**
I would like to have an embeddings Endpoint like the OpenAI (https://platform.openai.com/docs/guides/embeddings)

**Describe the solution you'd like**
A new route /v1/embeddings that recieves text or a files and returns the embeddings

**Describe alternatives you've considered**
I think it should be just a wrapper of https://huggingface.co/hkunlp/instructor-large

**Why should this feature be added?**
Embeddings are important to create RAGs and general AI apps

**Examples**
RAG example using embeddings: https://pdf.aidev.run/

**Additional context**
I think it would be very very useful for TabbyAPI

**Comment by kir-gadjello** [comment]
I just use https://github.com/michaelfeil/infinity on cpu

**Comment by bdashore3** [comment]
Closing due to implementation of infinity-emb on recent commits
