### ISSUE TITLE
[REQUEST] load model from arbitrary directory not just relative path

### ISSUE THREAD

**Issue by mmg10** [theroyallab/tabbyAPI#70]
**Is your feature request related to a problem? Please describe.**
I am using tabbyapi with kserve. Kserve always downloads model to /mnt/models

**Describe the solution you'd like**
I want to use the config.yml file with model/host specs but the model must be loaded from the /mnt/models (or any other directory). Maybe specifying the full path in the model_dir path inside the config.yml file.
 
**Describe alternatives you've considered**
I manually modified the containers CMD argument to force model download via huggingface-cli and then python start.py, but this is a dirty hack. 

**Why should this feature be added?**
This will eliminate the startup probes error in kubernetes.

**Examples**
No particular one

**Additional context**
loading models via the api is not an option in production/k8s environment in my case

**Comment by bdashore3** [comment]
You can specify the full path under the `model_dir` option. In your case, it'll be `model_dir: /mnt/models` inside your `config.yml` file.

In addition, you can also pass arguments on startup. Here's an example:
`python start.py --model_dir /mnt/models --model <your model here>`

**Comment by mmg10** [comment]
Thanks. I thought it was a relative path
