### ISSUE TITLE
[REQUEST] Please add an example chat completion template or some advice on how to make one.

### ISSUE THREAD

**Issue by NewtonTrendy** [theroyallab/tabbyAPI#74]

**Comment by bdashore3** [comment]
Please read the [Wiki](https://github.com/theroyallab/tabbyAPI/wiki/4.-API#4c-chat-completions) which links to HuggingFace's documentation. It's 1:1 to what TabbyAPI uses for chat templates. You can also look at the templates folder in this repository or [the chat templates repository](https://github.com/theroyallab/llm-prompt-templates) for examples.

Also please fill out the issue template next time. Closing this issue.
