### ISSUE TITLE
[REQUEST] Add finish_reason to the response

### ISSUE THREAD

**Issue by ikarth** [theroyallab/tabbyAPI#83]
**Is your feature request related to a problem? Please describe.**
Right now, the only `finish_reason` reported seems to be either None or Generated.
https://github.com/theroyallab/tabbyAPI/blob/7006fa4cc85158f76db4a68c2d20cb75eb367a8a/endpoints/OAI/utils/chat_completion.py#L60

The [OpenAI API](https://platform.openai.com/docs/api-reference/chat/streaming) is a little more expressive on this point:

> *finish_reason (string or null)*
>The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence, `length` if the maximum number of tokens specified in the request was reached, `content_filter` if content was omitted due to a flag from our content filters, `tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.

It's a flag that a number of projects use to check if the response was length-limited or hit the actual stop sequence. 

**Describe the solution you'd like**
Return `stop` or `length` from [ChatCompletionRespChoice](https://github.com/theroyallab/tabbyAPI/blob/7006fa4cc85158f76db4a68c2d20cb75eb367a8a/endpoints/OAI/utils/chat_completion.py#L60), ChatCompletionStreamChoice, [CompletionRespChoice](https://github.com/theroyallab/tabbyAPI/blob/7006fa4cc85158f76db4a68c2d20cb75eb367a8a/endpoints/OAI/utils/completion.py#L39).

Probably requires changes to [generate_gen()](https://github.com/theroyallab/tabbyAPI/blob/7006fa4cc85158f76db4a68c2d20cb75eb367a8a/backends/exllamav2/model.py#L987) to get the reason for generation completion.
Might need changes to the few places [finish_reason is used internally](https://github.com/theroyallab/tabbyAPI/blob/7006fa4cc85158f76db4a68c2d20cb75eb367a8a/endpoints/OAI/utils/chat_completion.py#L89).

**Describe alternatives you've considered**
Since this affects downstream applications, the most obvious workaround I can think of is to modify those libraries to estimate completion (counting tokens, etc.) rather than directly getting it from the API response.

**Why should this feature be added?**
Being able to get the response stopping reason makes it a lot easier to manage the length of the response in an automated way.  A number of frameworks (e.g., [DSPy](https://github.com/stanfordnlp/dspy/blob/6f004cc5fd43a1802ee84b90e3e78757b420a861/dsp/modules/gpt3.py#L191)) assume the OpenAI behavior, so not having it breaks OpenAI compatibility and makes it harder to use TabbyAPI as a drop-in replacement.

**Comment by bdashore3** [comment]
I never knew that libraries actually check that. The chat completions API can support this behavior, but the legacy completions API cannot due to sending `[DONE]` when a stream is finished. If there's any other method to replicate this behavior in legacy completions, I'd be happy to add it.

**Comment by bdashore3** [comment]
Fixed in 5c7fc69. Completions also has a `finish_reason`, so I return that before `[DONE]` is sent before closing the request stream.
