### ISSUE TITLE
[REQUEST] Endpoint to verify type of API key

### ISSUE THREAD

**Issue by Dakraid** [theroyallab/tabbyAPI#84]
I'm currently working on an implementation for SillyTavern to switch models on the fly for TabbyAPI. I came across one issue though, which is that I need to verify what type of API key the user has stored.

To test this without potential side effects by calling one of the protected endpoints, I propose the inclusion of a simple endpoint that takes in the API key and responds with a simple response that tells if the key is invalid, user, or admin ie.

```
{
	"result": "admin",
}
```

This would simplify the interaction and potentially allow other applications to check for this as well without risking side effects (accidentally un/loading a model ie.)

**Comment by bdashore3** [comment]
Good idea, but please use the issue template next time.

**Comment by bdashore3** [comment]
In addition, if you want a loader: [ST-TabbyAPI-loader](https://github.com/theroyallab/ST-tabbyAPI-loader) is available to use. I'd love to get this integrated into ST main as well.

**Comment by Dakraid** [comment]
> Good idea, but please use the issue template next time.

Sorry about the issue template, will do it next time.

> In addition, if you want a loader: [ST-TabbyAPI-loader](https://github.com/theroyallab/ST-tabbyAPI-loader) is available to use. I'd love to get this integrated into ST main as well.

Yeah, I wasn't aware of that when I started. I would happily take over and integrate the functionality after completing it, I think everyone benefits from that.

**Comment by bdashore3** [comment]
Endpoint added in 3c08f46c51d4137a6d067bf4160bb7d0ed451c86. As for the loader, please open a separate issue [there](https://github.com/theroyallab/ST-tabbyAPI-loader/issues).
