### ISSUE TITLE
[BUG] Jinja template fails to render on _get_template_stop_strings due to missing messages

### ISSUE THREAD

**Issue by AndrewRyanChama** [theroyallab/tabbyAPI#92]
**Describe the bug**
This change added what seems to be a tabbyapi-exclusive proprietary way of adding stop strings in the jinja template.
https://github.com/theroyallab/tabbyAPI/commit/dc456f4cc21efaaeeeefd2fec492ca7afb819320

Unfortunately, this code in _get_template_stop_strings crashes on a number of jinja templates that are working with huggingface transformers, because those templates assume the existence of the messages attribute.  For example, the official llama2 template: 
https://github.com/chujiezheng/chat_templates/blob/main/chat_templates/llama-2-chat.jinja#L1
https://github.com/huggingface/transformers/blob/c9f6e5e35156e068b227dd9b15521767f6afd4d2/src/transformers/models/llama/tokenization_llama_fast.py#L211

This is because this _get_template_stop_strings triggers a template render when jinja fetches the module attributes, but it doesn't pass any input params in.  The other prompt templates in this repo don't fail directly because they only interact with the messages attribute with a forEach loop which just becomes a noop

[The documentation](https://github.com/theroyallab/tabbyAPI/wiki/4.-API#4c-chat-completions) says that huggingface-compatible templates should work here, as well as templates that are included in model.json.  Given that, in my IMO I feel like it's totally unreasonable that templates should have additional undocumented functionality bolted on, and that this feature should be totally reverted.  But even if you decide to keep it then it should at least be compatible with templates that are made for HF

**To Reproduce**
use the template
```
{% if messages[0]['role'] == 'system' %}{% set loop_messages = messages[1:] %}{% set system_message = messages[0]['content'] %}{% elif USE_DEFAULT_PROMPT == true and not '<<SYS>>' in messages[0]['content'] %}{% set loop_messages = messages %}{% set system_message = 'DEFAULT_SYSTEM_MESSAGE' %}{% else %}{% set loop_messages = messages %}{% set system_message = false %}{% endif %}{% for message in loop_messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if loop.index0 == 0 and system_message != false %}{% set content = '<<SYS>>\n' + system_message + '\n<</SYS>>\n\n' + message['content'] %}{% else %}{% set content = message['content'] %}{% endif %}{% if message['role'] == 'user' %}{{ bos_token + '[INST] ' + content.strip() + ' [/INST]' }}{% elif message['role'] == 'system' %}{{ '<<SYS>>\n' + content.strip() + '\n<</SYS>>\n\n' }}{% elif message['role'] == 'assistant' %}{{ ' '  + content.strip() + ' ' + eos_token }}{% endif %}{% endfor %}
```

**Expected behavior**
it shouln't fail

**Logs**
If applicable, add logs and tracebacks to help explain your problem.

**System info** (Bugs without this information will go lower on our priority list!)
 - OS: [ex. Windows]
 - Python version: [ex. 3.11]
 - CUDA/ROCm version: [ex. 12.x]
 - Python version: [ex. 3.11]

**Additional context**

**Comment by DocShotgun** [comment]
The stopping strings change in dc456f4 is intended to be entirely optional and intended to provide a way to address https://github.com/theroyallab/tabbyAPI/issues/89 while maintaining the flexibility of the jinja2 templates. If it's breaking compatibility with huggingface-compatible templates that were previously functional, that would be a bug that needs to be addressed. So far able to reproduce this with the linked template.

**Comment by AndrewRyanChama** [comment]
thanks for the quick fix!
