### ISSUE TITLE
[BUG] generate_chat_completion not set abort_event

### ISSUE THREAD

**Issue by litlei0668** [theroyallab/tabbyAPI#98]
generate_chat_completion not set abort_event.
when request is disconnect ,and the exllama generater is run. and next request will error.

**Comment by litlei0668** [comment]
ERROR:    Traceback (most recent call last):
ERROR:      File "/data/tabbyAPI/endpoints/OAI/utils/chat_completion.py", line 212, in generate_chat_completion
ERROR:        generation = await model.container.generate(
ERROR:      File "/data/tabbyAPI/backends/exllamav2/model.py", line 622, in generate
ERROR:        async for generation in self.generate_gen(prompt, **kwargs):
ERROR:      File "/data/tabbyAPI/backends/exllamav2/model.py", line 677, in generate_gen
ERROR:        async for value in iterate_in_threadpool(sync_generator):
ERROR:      File "/data/tabbyAPI/common/concurrency.py", line 34, in iterate_in_threadpool
ERROR:        yield await asyncio.to_thread(gen_next, generator)
ERROR:      File "/opt/conda/lib/python3.10/asyncio/threads.py", line 25, in to_thread
ERROR:        return await loop.run_in_executor(None, func_call)
ERROR:      File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run
ERROR:        result = self.fn(*self.args, **self.kwargs)
ERROR:      File "/data/tabbyAPI/common/concurrency.py", line 24, in gen_next
ERROR:        return next(generator)
ERROR:      File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
ERROR:        response = gen.send(None)
ERROR:      File "/data/tabbyAPI/backends/exllamav2/model.py", line 982, in generate_gen_sync
ERROR:        self.generator.begin_stream_ex(
ERROR:      File "/data/tabbyAPI/exllamav2/generator/streaming.py", line 296, in begin_stream_ex
ERROR:        self._gen_begin_reuse(input_ids, gen_settings)
ERROR:      File "/data/tabbyAPI/exllamav2/generator/streaming.py", line 640, in _gen_begin_reuse
ERROR:        if reuse \< in_tokens.shape[-1]: self._gen_feed_tokens(in_tokens[:, reuse:], gen_settings)
ERROR:      File "/data/tabbyAPI/exllamav2/generator/streaming.py", line 660, in _gen_feed_tokens
ERROR:        self.model.forward(self.sequence_ids[:, start : -1],
ERROR:      File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
ERROR:        return func(*args, **kwargs)
ERROR:      File "/data/tabbyAPI/exllamav2/model.py", line 702, in forward
ERROR:        r, ls = self._forward(input_ids = input_ids[:, chunk_begin : chunk_end],
ERROR:      File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
ERROR:        return func(*args, **kwargs)
ERROR:      File "/data/tabbyAPI/exllamav2/model.py", line 784, in _forward
ERROR:        x = module.forward(x, cache = cache, attn_params = attn_params, past_len = past_len, loras = loras, **kwargs)
ERROR:      File "/data/tabbyAPI/exllamav2/attn.py", line 451, in forward
ERROR:        return self.forward_torch(hidden_states,
ERROR:      File "/data/tabbyAPI/exllamav2/attn.py", line 782, in forward_torch
ERROR:        if attn_mask is not None: attn_weights = attn_weights + attn_mask
ERROR:    RuntimeError: The size of tensor a (1171) must match the size of tensor b (1170) at non-singleton dimension 3
ERROR:    Sent to request: Chat completion aborted. Maybe the model was unloaded? Please check the server console.
INFO:     111.202.44.123:56063 - "POST /v1/chat/completions HTTP/1.1" 503
ERROR:    Chat completion generation cancelled by user.

**Comment by bdashore3** [comment]
Resolved in #109
